export const COUNTRY_TO_DEMONYM: Record<string, string> = {
  "Afghanistan": "Afghan", "Albania": "Albanian", "Algeria": "Algerian", "United States": "American", "USA": "American", "America": "American",
  "Andorra": "Andorran", "Angola": "Angolan", "Antigua and Barbuda": "Antiguan", "Argentina": "Argentine",
  "Armenia": "Armenian", "Australia": "Australian", "Austria": "Austrian", "Azerbaijan": "Azerbaijani",
  "Bahamas": "Bahamian", "Bahrain": "Bahraini", "Bangladesh": "Bangladeshi", "Barbados": "Barbadian",
  "Belarus": "Belarusian", "Belgium": "Belgian", "Belize": "Belizean", "Benin": "Beninese",
  "Bhutan": "Bhutanese", "Bolivia": "Bolivian", "Bosnia and Herzegovina": "Bosnian", "Bosnia": "Bosnian",
  "Botswana": "Botswanan", "Brazil": "Brazilian", "Brunei": "Bruneian", "Bulgaria": "Bulgarian",
  "Burkina Faso": "Burkinabe", "Myanmar": "Burmese", "Burma": "Burmese", "Burundi": "Burundian",
  "Cabo Verde": "Cabo Verdean", "Cape Verde": "Cabo Verdean", "Cambodia": "Cambodian", "Cameroon": "Cameroonian",
  "Canada": "Canadian", "Central African Republic": "Central African", "Chad": "Chadian", "Chile": "Chilean",
  "China": "Chinese", "Colombia": "Colombian", "Comoros": "Comorian", "Congo": "Congolese",
  "Costa Rica": "Costa Rican", "Croatia": "Croatian", "Cuba": "Cuban", "Cyprus": "Cypriot",
  "Czech Republic": "Czech", "Czechia": "Czech", "Denmark": "Danish", "Djibouti": "Djiboutian",
  "Dominican Republic": "Dominican", "Netherlands": "Dutch", "Holland": "Dutch",
  "East Timor": "East Timorese", "Timor-Leste": "East Timorese", "Ecuador": "Ecuadorian",
  "Egypt": "Egyptian", "United Arab Emirates": "Emirati", "UAE": "Emirati",
  "Equatorial Guinea": "Equatorial Guinean", "Eritrea": "Eritrean", "Estonia": "Estonian",
  "Eswatini": "Eswatini", "Swaziland": "Eswatini", "Ethiopia": "Ethiopian",
  "Fiji": "Fijian", "Philippines": "Filipino", "Finland": "Finnish", "France": "French",
  "Gabon": "Gabonese", "Gambia": "Gambian", "Georgia": "Georgian", "Germany": "German",
  "Ghana": "Ghanaian", "Greece": "Greek", "Grenada": "Grenadian", "Guatemala": "Guatemalan",
  "Guinea": "Guinean", "Guyana": "Guyanese", "Haiti": "Haitian", "Honduras": "Honduran",
  "Hungary": "Hungarian", "Iceland": "Icelandic", "India": "Indian", "Indonesia": "Indonesian",
  "Iran": "Iranian", "Iraq": "Iraqi", "Ireland": "Irish", "Israel": "Israeli", "Italy": "Italian",
  "Ivory Coast": "Ivorian", "Côte d'Ivoire": "Ivorian", "Jamaica": "Jamaican", "Japan": "Japanese",
  "Jordan": "Jordanian", "Kazakhstan": "Kazakh", "Kenya": "Kenyan", "Kiribati": "Kiribati",
  "Kosovo": "Kosovar", "Kuwait": "Kuwaiti", "Kyrgyzstan": "Kyrgyz", "Laos": "Lao",
  "Latvia": "Latvian", "Lebanon": "Lebanese", "Liberia": "Liberian", "Libya": "Libyan",
  "Liechtenstein": "Liechtenstein", "Lithuania": "Lithuanian", "Luxembourg": "Luxembourgish",
  "Madagascar": "Malagasy", "Malawi": "Malawian", "Malaysia": "Malaysian", "Maldives": "Maldivian",
  "Mali": "Malian", "Malta": "Maltese", "Marshall Islands": "Marshallese", "Mauritania": "Mauritanian",
  "Mauritius": "Mauritian", "Mexico": "Mexican", "Micronesia": "Micronesian", "Moldova": "Moldovan",
  "Monaco": "Monacan", "Mongolia": "Mongolian", "Montenegro": "Montenegrin", "Morocco": "Moroccan",
  "Mozambique": "Mozambican", "Namibia": "Namibian", "Nauru": "Nauruan", "Nepal": "Nepali",
  "New Zealand": "New Zealander", "Nicaragua": "Nicaraguan", "Nigeria": "Nigerian", "Niger": "Nigerien",
  "North Korea": "North Korean", "North Macedonia": "North Macedonian", "Norway": "Norwegian",
  "Oman": "Omani", "Pakistan": "Pakistani", "Palau": "Palauan", "Palestine": "Palestinian",
  "Panama": "Panamanian", "Papua New Guinea": "Papua New Guinean", "Paraguay": "Paraguayan",
  "Peru": "Peruvian", "Poland": "Polish", "Portugal": "Portuguese", "Qatar": "Qatari",
  "Romania": "Romanian", "Russia": "Russian", "Rwanda": "Rwandan",
  "Saint Kitts and Nevis": "Saint Kitts and Nevis", "Saint Lucia": "Saint Lucian",
  "El Salvador": "Salvadoran", "Samoa": "Samoan", "San Marino": "San Marinese",
  "São Tomé and Príncipe": "Sao Tomean", "Saudi Arabia": "Saudi", "Senegal": "Senegalese",
  "Serbia": "Serbian", "Seychelles": "Seychellois", "Sierra Leone": "Sierra Leonean",
  "Singapore": "Singaporean", "Slovakia": "Slovak", "Slovenia": "Slovenian",
  "Solomon Islands": "Solomon Islander", "Somalia": "Somali", "South Africa": "South African",
  "South Korea": "South Korean", "Korea": "South Korean", "South Sudan": "South Sudanese",
  "Spain": "Spanish", "Sri Lanka": "Sri Lankan", "Sudan": "Sudanese", "Suriname": "Surinamese",
  "Sweden": "Swedish", "Switzerland": "Swiss", "Syria": "Syrian", "Tajikistan": "Tajik",
  "Tanzania": "Tanzanian", "Thailand": "Thai", "Togo": "Togolese", "Tonga": "Tongan",
  "Trinidad and Tobago": "Trinidadian", "Tunisia": "Tunisian", "Turkey": "Turkish", "Türkiye": "Turkish",
  "Turkmenistan": "Turkmen", "Tuvalu": "Tuvaluan", "Uganda": "Ugandan", "Ukraine": "Ukrainian",
  "Uruguay": "Uruguayan", "Uzbekistan": "Uzbek", "Vanuatu": "Vanuatuan", "Venezuela": "Venezuelan",
  "Vietnam": "Vietnamese", "Viet Nam": "Vietnamese", "Yemen": "Yemeni", "Zambia": "Zambian", "Zimbabwe": "Zimbabwean",
  "United Kingdom": "British", "UK": "British", "England": "British", "Scotland": "British",
};

export function normalizeNationality(value: string): string {
  if (!value) return value;
  const trimmed = value.trim();
  if (ALL_NATIONALITIES.includes(trimmed)) return trimmed;
  const mapped = COUNTRY_TO_DEMONYM[trimmed];
  if (mapped) return mapped;
  const lower = trimmed.toLowerCase();
  for (const [country, demonym] of Object.entries(COUNTRY_TO_DEMONYM)) {
    if (country.toLowerCase() === lower) return demonym;
  }
  for (const nat of ALL_NATIONALITIES) {
    if (nat.toLowerCase() === lower) return nat;
  }
  return trimmed;
}

export const ALL_NATIONALITIES = [
  "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan", "Antiguan", "Argentine",
  "Armenian", "Australian", "Austrian", "Azerbaijani", "Bahamian", "Bahraini", "Bangladeshi",
  "Barbadian", "Belarusian", "Belgian", "Belizean", "Beninese", "Bhutanese", "Bolivian",
  "Bosnian", "Botswanan", "Brazilian", "Bruneian", "Bulgarian", "Burkinabe", "Burmese",
  "Burundian", "Cabo Verdean", "Cambodian", "Cameroonian", "Canadian", "Central African",
  "Chadian", "Chilean", "Chinese", "Colombian", "Comorian", "Congolese", "Costa Rican",
  "Croatian", "Cuban", "Cypriot", "Czech", "Danish", "Djiboutian", "Dominican", "Dutch",
  "East Timorese", "Ecuadorian", "Egyptian", "Emirati", "Equatorial Guinean", "Eritrean",
  "Estonian", "Eswatini", "Ethiopian", "Fijian", "Filipino", "Finnish", "French", "Gabonese",
  "Gambian", "Georgian", "German", "Ghanaian", "Greek", "Grenadian", "Guatemalan", "Guinean",
  "Guyanese", "Haitian", "Honduran", "Hungarian", "Icelandic", "Indian", "Indonesian", "Iranian",
  "Iraqi", "Irish", "Israeli", "Italian", "Ivorian", "Jamaican", "Japanese", "Jordanian",
  "Kazakh", "Kenyan", "Kiribati", "Kosovar", "Kuwaiti", "Kyrgyz", "Lao", "Latvian", "Lebanese",
  "Liberian", "Libyan", "Liechtenstein", "Lithuanian", "Luxembourgish", "Malagasy", "Malawian",
  "Malaysian", "Maldivian", "Malian", "Maltese", "Marshallese", "Mauritanian", "Mauritian",
  "Mexican", "Micronesian", "Moldovan", "Monacan", "Mongolian", "Montenegrin", "Moroccan",
  "Mozambican", "Namibian", "Nauruan", "Nepali", "New Zealander", "Nicaraguan", "Nigerian",
  "Nigerien", "North Korean", "North Macedonian", "Norwegian", "Omani", "Pakistani", "Palauan",
  "Palestinian", "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian", "Polish",
  "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan", "Saint Kitts and Nevis",
  "Saint Lucian", "Salvadoran", "Samoan", "San Marinese", "Sao Tomean", "Saudi", "Senegalese",
  "Serbian", "Seychellois", "Sierra Leonean", "Singaporean", "Slovak", "Slovenian",
  "Solomon Islander", "Somali", "South African", "South Korean", "South Sudanese", "Spanish",
  "Sri Lankan", "Sudanese", "Surinamese", "Swedish", "Swiss", "Syrian", "Tajik", "Tanzanian",
  "Thai", "Togolese", "Tongan", "Trinidadian", "Tunisian", "Turkish", "Turkmen", "Tuvaluan",
  "Ugandan", "Ukrainian", "Uruguayan", "Uzbek", "Vanuatuan", "Venezuelan", "Vietnamese",
  "Yemeni", "Zambian", "Zimbabwean",
];

export const PHONE_CODES = [
  { code: "+93", country: "AF", label: "🇦🇫 +93" },
  { code: "+355", country: "AL", label: "🇦🇱 +355" },
  { code: "+213", country: "DZ", label: "🇩🇿 +213" },
  { code: "+1", country: "US", label: "🇺🇸 +1" },
  { code: "+376", country: "AD", label: "🇦🇩 +376" },
  { code: "+244", country: "AO", label: "🇦🇴 +244" },
  { code: "+54", country: "AR", label: "🇦🇷 +54" },
  { code: "+374", country: "AM", label: "🇦🇲 +374" },
  { code: "+61", country: "AU", label: "🇦🇺 +61" },
  { code: "+43", country: "AT", label: "🇦🇹 +43" },
  { code: "+994", country: "AZ", label: "🇦🇿 +994" },
  { code: "+973", country: "BH", label: "🇧🇭 +973" },
  { code: "+880", country: "BD", label: "🇧🇩 +880" },
  { code: "+375", country: "BY", label: "🇧🇾 +375" },
  { code: "+32", country: "BE", label: "🇧🇪 +32" },
  { code: "+501", country: "BZ", label: "🇧🇿 +501" },
  { code: "+229", country: "BJ", label: "🇧🇯 +229" },
  { code: "+975", country: "BT", label: "🇧🇹 +975" },
  { code: "+591", country: "BO", label: "🇧🇴 +591" },
  { code: "+387", country: "BA", label: "🇧🇦 +387" },
  { code: "+267", country: "BW", label: "🇧🇼 +267" },
  { code: "+55", country: "BR", label: "🇧🇷 +55" },
  { code: "+673", country: "BN", label: "🇧🇳 +673" },
  { code: "+359", country: "BG", label: "🇧🇬 +359" },
  { code: "+226", country: "BF", label: "🇧🇫 +226" },
  { code: "+257", country: "BI", label: "🇧🇮 +257" },
  { code: "+855", country: "KH", label: "🇰🇭 +855" },
  { code: "+237", country: "CM", label: "🇨🇲 +237" },
  { code: "+1", country: "CA", label: "🇨🇦 +1" },
  { code: "+238", country: "CV", label: "🇨🇻 +238" },
  { code: "+236", country: "CF", label: "🇨🇫 +236" },
  { code: "+235", country: "TD", label: "🇹🇩 +235" },
  { code: "+56", country: "CL", label: "🇨🇱 +56" },
  { code: "+86", country: "CN", label: "🇨🇳 +86" },
  { code: "+57", country: "CO", label: "🇨🇴 +57" },
  { code: "+269", country: "KM", label: "🇰🇲 +269" },
  { code: "+242", country: "CG", label: "🇨🇬 +242" },
  { code: "+243", country: "CD", label: "🇨🇩 +243" },
  { code: "+506", country: "CR", label: "🇨🇷 +506" },
  { code: "+385", country: "HR", label: "🇭🇷 +385" },
  { code: "+53", country: "CU", label: "🇨🇺 +53" },
  { code: "+357", country: "CY", label: "🇨🇾 +357" },
  { code: "+420", country: "CZ", label: "🇨🇿 +420" },
  { code: "+45", country: "DK", label: "🇩🇰 +45" },
  { code: "+253", country: "DJ", label: "🇩🇯 +253" },
  { code: "+593", country: "EC", label: "🇪🇨 +593" },
  { code: "+20", country: "EG", label: "🇪🇬 +20" },
  { code: "+503", country: "SV", label: "🇸🇻 +503" },
  { code: "+240", country: "GQ", label: "🇬🇶 +240" },
  { code: "+291", country: "ER", label: "🇪🇷 +291" },
  { code: "+372", country: "EE", label: "🇪🇪 +372" },
  { code: "+251", country: "ET", label: "🇪🇹 +251" },
  { code: "+679", country: "FJ", label: "🇫🇯 +679" },
  { code: "+358", country: "FI", label: "🇫🇮 +358" },
  { code: "+33", country: "FR", label: "🇫🇷 +33" },
  { code: "+241", country: "GA", label: "🇬🇦 +241" },
  { code: "+220", country: "GM", label: "🇬🇲 +220" },
  { code: "+995", country: "GE", label: "🇬🇪 +995" },
  { code: "+49", country: "DE", label: "🇩🇪 +49" },
  { code: "+233", country: "GH", label: "🇬🇭 +233" },
  { code: "+30", country: "GR", label: "🇬🇷 +30" },
  { code: "+502", country: "GT", label: "🇬🇹 +502" },
  { code: "+224", country: "GN", label: "🇬🇳 +224" },
  { code: "+592", country: "GY", label: "🇬🇾 +592" },
  { code: "+509", country: "HT", label: "🇭🇹 +509" },
  { code: "+504", country: "HN", label: "🇭🇳 +504" },
  { code: "+36", country: "HU", label: "🇭🇺 +36" },
  { code: "+354", country: "IS", label: "🇮🇸 +354" },
  { code: "+91", country: "IN", label: "🇮🇳 +91" },
  { code: "+62", country: "ID", label: "🇮🇩 +62" },
  { code: "+98", country: "IR", label: "🇮🇷 +98" },
  { code: "+964", country: "IQ", label: "🇮🇶 +964" },
  { code: "+353", country: "IE", label: "🇮🇪 +353" },
  { code: "+972", country: "IL", label: "🇮🇱 +972" },
  { code: "+39", country: "IT", label: "🇮🇹 +39" },
  { code: "+225", country: "CI", label: "🇨🇮 +225" },
  { code: "+1876", country: "JM", label: "🇯🇲 +1876" },
  { code: "+81", country: "JP", label: "🇯🇵 +81" },
  { code: "+962", country: "JO", label: "🇯🇴 +962" },
  { code: "+7", country: "KZ", label: "🇰🇿 +7" },
  { code: "+254", country: "KE", label: "🇰🇪 +254" },
  { code: "+686", country: "KI", label: "🇰🇮 +686" },
  { code: "+383", country: "XK", label: "🇽🇰 +383" },
  { code: "+965", country: "KW", label: "🇰🇼 +965" },
  { code: "+996", country: "KG", label: "🇰🇬 +996" },
  { code: "+856", country: "LA", label: "🇱🇦 +856" },
  { code: "+371", country: "LV", label: "🇱🇻 +371" },
  { code: "+961", country: "LB", label: "🇱🇧 +961" },
  { code: "+266", country: "LS", label: "🇱🇸 +266" },
  { code: "+231", country: "LR", label: "🇱🇷 +231" },
  { code: "+218", country: "LY", label: "🇱🇾 +218" },
  { code: "+423", country: "LI", label: "🇱🇮 +423" },
  { code: "+370", country: "LT", label: "🇱🇹 +370" },
  { code: "+352", country: "LU", label: "🇱🇺 +352" },
  { code: "+261", country: "MG", label: "🇲🇬 +261" },
  { code: "+265", country: "MW", label: "🇲🇼 +265" },
  { code: "+60", country: "MY", label: "🇲🇾 +60" },
  { code: "+960", country: "MV", label: "🇲🇻 +960" },
  { code: "+223", country: "ML", label: "🇲🇱 +223" },
  { code: "+356", country: "MT", label: "🇲🇹 +356" },
  { code: "+692", country: "MH", label: "🇲🇭 +692" },
  { code: "+222", country: "MR", label: "🇲🇷 +222" },
  { code: "+230", country: "MU", label: "🇲🇺 +230" },
  { code: "+52", country: "MX", label: "🇲🇽 +52" },
  { code: "+691", country: "FM", label: "🇫🇲 +691" },
  { code: "+373", country: "MD", label: "🇲🇩 +373" },
  { code: "+377", country: "MC", label: "🇲🇨 +377" },
  { code: "+976", country: "MN", label: "🇲🇳 +976" },
  { code: "+382", country: "ME", label: "🇲🇪 +382" },
  { code: "+212", country: "MA", label: "🇲🇦 +212" },
  { code: "+258", country: "MZ", label: "🇲🇿 +258" },
  { code: "+95", country: "MM", label: "🇲🇲 +95" },
  { code: "+264", country: "NA", label: "🇳🇦 +264" },
  { code: "+674", country: "NR", label: "🇳🇷 +674" },
  { code: "+977", country: "NP", label: "🇳🇵 +977" },
  { code: "+31", country: "NL", label: "🇳🇱 +31" },
  { code: "+64", country: "NZ", label: "🇳🇿 +64" },
  { code: "+505", country: "NI", label: "🇳🇮 +505" },
  { code: "+227", country: "NE", label: "🇳🇪 +227" },
  { code: "+234", country: "NG", label: "🇳🇬 +234" },
  { code: "+850", country: "KP", label: "🇰🇵 +850" },
  { code: "+389", country: "MK", label: "🇲🇰 +389" },
  { code: "+47", country: "NO", label: "🇳🇴 +47" },
  { code: "+968", country: "OM", label: "🇴🇲 +968" },
  { code: "+92", country: "PK", label: "🇵🇰 +92" },
  { code: "+680", country: "PW", label: "🇵🇼 +680" },
  { code: "+970", country: "PS", label: "🇵🇸 +970" },
  { code: "+507", country: "PA", label: "🇵🇦 +507" },
  { code: "+675", country: "PG", label: "🇵🇬 +675" },
  { code: "+595", country: "PY", label: "🇵🇾 +595" },
  { code: "+51", country: "PE", label: "🇵🇪 +51" },
  { code: "+63", country: "PH", label: "🇵🇭 +63" },
  { code: "+48", country: "PL", label: "🇵🇱 +48" },
  { code: "+351", country: "PT", label: "🇵🇹 +351" },
  { code: "+974", country: "QA", label: "🇶🇦 +974" },
  { code: "+40", country: "RO", label: "🇷🇴 +40" },
  { code: "+7", country: "RU", label: "🇷🇺 +7" },
  { code: "+250", country: "RW", label: "🇷🇼 +250" },
  { code: "+966", country: "SA", label: "🇸🇦 +966" },
  { code: "+221", country: "SN", label: "🇸🇳 +221" },
  { code: "+381", country: "RS", label: "🇷🇸 +381" },
  { code: "+248", country: "SC", label: "🇸🇨 +248" },
  { code: "+232", country: "SL", label: "🇸🇱 +232" },
  { code: "+65", country: "SG", label: "🇸🇬 +65" },
  { code: "+421", country: "SK", label: "🇸🇰 +421" },
  { code: "+386", country: "SI", label: "🇸🇮 +386" },
  { code: "+677", country: "SB", label: "🇸🇧 +677" },
  { code: "+252", country: "SO", label: "🇸🇴 +252" },
  { code: "+27", country: "ZA", label: "🇿🇦 +27" },
  { code: "+82", country: "KR", label: "🇰🇷 +82" },
  { code: "+211", country: "SS", label: "🇸🇸 +211" },
  { code: "+34", country: "ES", label: "🇪🇸 +34" },
  { code: "+94", country: "LK", label: "🇱🇰 +94" },
  { code: "+249", country: "SD", label: "🇸🇩 +249" },
  { code: "+597", country: "SR", label: "🇸🇷 +597" },
  { code: "+46", country: "SE", label: "🇸🇪 +46" },
  { code: "+41", country: "CH", label: "🇨🇭 +41" },
  { code: "+963", country: "SY", label: "🇸🇾 +963" },
  { code: "+992", country: "TJ", label: "🇹🇯 +992" },
  { code: "+255", country: "TZ", label: "🇹🇿 +255" },
  { code: "+66", country: "TH", label: "🇹🇭 +66" },
  { code: "+228", country: "TG", label: "🇹🇬 +228" },
  { code: "+676", country: "TO", label: "🇹🇴 +676" },
  { code: "+1868", country: "TT", label: "🇹🇹 +1868" },
  { code: "+216", country: "TN", label: "🇹🇳 +216" },
  { code: "+90", country: "TR", label: "🇹🇷 +90" },
  { code: "+993", country: "TM", label: "🇹🇲 +993" },
  { code: "+688", country: "TV", label: "🇹🇻 +688" },
  { code: "+256", country: "UG", label: "🇺🇬 +256" },
  { code: "+380", country: "UA", label: "🇺🇦 +380" },
  { code: "+971", country: "AE", label: "🇦🇪 +971" },
  { code: "+44", country: "GB", label: "🇬🇧 +44" },
  { code: "+598", country: "UY", label: "🇺🇾 +598" },
  { code: "+998", country: "UZ", label: "🇺🇿 +998" },
  { code: "+678", country: "VU", label: "🇻🇺 +678" },
  { code: "+58", country: "VE", label: "🇻🇪 +58" },
  { code: "+84", country: "VN", label: "🇻🇳 +84" },
  { code: "+967", country: "YE", label: "🇾🇪 +967" },
  { code: "+260", country: "ZM", label: "🇿🇲 +260" },
  { code: "+263", country: "ZW", label: "🇿🇼 +263" },
];
